### ISSUE TITLE
Updating conda-forge

### ISSUE THREAD

**Issue by joserezende** [online-ml/river#1624]
The version available on anaconda is from more than a year ago, it would be possible to update conda-forge? Thanks for now.

**Comment by ProfLeao** [comment]
Watching

**Comment by MaxHalford** [comment]
Hey there. Actually we were the ones who first put River on Anaconda. It's too bad the person who did that didn't follow up with the new versions.

**Comment by ProfLeao** [comment]
How unfortunate! I'll see what I can do about that.

**Comment by ProfLeao** [comment]
The conda-forge-admin gave me the error listed below.

https://github.com/conda-forge/river-feedstock/pull/26#issuecomment-2423477179

As I'm not a developer of the package, I'd like to know if there's a problem with removing these restrictions and leaving them as:

```yaml
requirements:
  host:
    - cython
    - numpy
    - setuptools
    - wheel
    - setuptools-rust
    - pip
  run:
    - numpy >=1.23.0,<2.0.0
    - scipy >=1.12.1,<2.0.0
    - pandas >=2.1.0,<3.0.0
```
